name: PR Check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request_target:
    branches:
      - main
    paths-ignore: # Skip run for security reasons
      - .github/workflows/**/*.py
    types:
      - opened
      - synchronize
      - closed
      - labeled

jobs:
  pr-check:
    runs-on: ubuntu-latest 

    # To reduce useless runs
    if: |
      (github.event.action != 'closed' || github.event.pull_request.merged) &&
      (github.event.action != 'labeled' || github.event.label.name == 'recheck')

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed files
        id: changed-files
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List changed files
        run: |
          echo "Added files:"
          echo "${{ steps.changed-files.outputs.added }}"
          echo "All changed files:"
          echo "${{ steps.changed-files.outputs.all }}"
          echo "Deleted files:"
          echo "${{ steps.changed-files.outputs.deleted }}"
      - name: Write changed files to JSON
        run: |
          mkdir -p .github/outputs
          echo '${{ steps.changed-files.outputs.added }}' > .github/outputs/added_files.json
          echo '${{ steps.changed-files.outputs.all }}' > .github/outputs/all_changed_files.json
          echo '${{ steps.changed-files.outputs.deleted }}' > .github/outputs/deleted_files.json
        shell: bash

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # - name: Setup Requirements
      #   run: |
      #     pip install -r scripts/requirements.txt
      
      # - name: Run Checker
      #   run: |
      #     python scripts/pr_check.py
